# Generated by Django 3.0.1 on 2021-01-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100)),
                ('donor_email', models.EmailField(max_length=100)),
                ('donor_DOB', models.DateField()),
                ('donor_gender', models.CharField(max_length=10)),
                ('donor_phone', models.CharField(max_length=10)),
                ('donor_address', models.CharField(max_length=100)),
                ('donor_blood_group', models.CharField(max_length=5)),
            ],
        ),
    ]
