# Generated by Django 3.2 on 2021-04-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor_Registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
